"""empty message

Revision ID: bb24ddb2daea
Revises: 251c1816d454
Create Date: 2021-05-31 22:40:21.858106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb24ddb2daea'
down_revision = '251c1816d454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'image_url')
    # ### end Alembic commands ###
