"""empty message

Revision ID: c4f1de41386b
Revises: 314eed0c07a8
Create Date: 2021-05-31 16:39:05.637105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f1de41386b'
down_revision = '314eed0c07a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cities_coutry_id_key', 'cities', type_='unique')
    op.drop_constraint('cities_name_key', 'cities', type_='unique')
    op.create_foreign_key(None, 'cities', 'countries', ['coutry_id'], ['id'])
    op.create_foreign_key(None, 'custom_destinations', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'custom_destinations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'default_destinations', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'events', 'custom_destinations', ['custom_destination_id'], ['id'])
    op.create_foreign_key(None, 'events', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'events', 'default_destinations', ['default_destination_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'default_destinations', type_='foreignkey')
    op.drop_constraint(None, 'custom_destinations', type_='foreignkey')
    op.drop_constraint(None, 'custom_destinations', type_='foreignkey')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.create_unique_constraint('cities_name_key', 'cities', ['name'])
    op.create_unique_constraint('cities_coutry_id_key', 'cities', ['coutry_id'])
    # ### end Alembic commands ###
