"""empty message

Revision ID: d7e70767ac42
Revises: bb24ddb2daea
Create Date: 2021-06-08 15:59:20.658404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e70767ac42'
down_revision = 'bb24ddb2daea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'distance')
    # ### end Alembic commands ###
